plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = "${mcversion}-${version_major}.${version_minor}.${version_patch}"
group = "${author}.${modid}"
archivesBaseName = "${modid}"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: project.mcp_channel, version: project.mcp_mappings
    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file("run/client").canonicalPath
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                wrenchfinder {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file("run/server").canonicalPath
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                wrenchfinder {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file("run/client").canonicalPath
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            args '--mod', archivesBaseName, '--all',
                '--existing', '"' + file('src/main/resources/') + '"',
                '--existing', '"' + file('src/generated/resources/') + '"',
                '--output', '"' + file('src/generated/resources/') + '"'

            mods {
                wrenchfinder {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    mavenCentral()
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.blamejared.com" }
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${mcversion}-${forgeversion}"

    implementation fg.deobf("me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}")

    compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}:api")
    // runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}")

    compileOnly fg.deobf("vazkii.botania:Botania:${botania}:api")
    compileOnly fg.deobf("curse.maven:l2-backpack-620229:${l2backpack_fileid}")
    compileOnly fg.deobf("curse.maven:l2library-620203:${l2library_fileid}")
    compileOnly fg.deobf("curse.maven:applied-energistics-2-223794:${ae2_fileid}")
    // runtimeOnly fg.deobf("org.appliedenergistics:guideme:20.1.14")
    // runtimeOnly fg.deobf("curse.maven:applied-energistics-2-223794:${ae2_fileid}")
    compileOnly fg.deobf("curse.maven:toms-storage-378609:${tomsstorage_fileid}")
    compileOnly fg.deobf("curse.maven:refined-storage-243076:${refinedstorage_fileid}")
    compileOnly fg.deobf("curse.maven:beyond-dimensions-1222890:${beyond_dimensions_fileid}")
}

jar {
    manifest {
        attributes([
            "Specification-Title": archivesBaseName,
            "Specification-Vendor": "${author}",
            "Specification-Version": "1",
            "Implementation-Title": archivesBaseName,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"${author}",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
