# org.gradle.java.home=C:/Program Files/Java/dragonwell-21
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
neo_version=26.1.2.21-beta
neo_version_range=[26.1.2.21-beta,)
minecraft_version_range=[26.1,)

mod_id=wrenchfinder
mod_name=Wrench Finder
mod_license=MIT
mod_version=1.1.0
mod_group_id=dev.polaris_light.wrenchfinder
mod_authors=Polaris_Light
mod_description=Wrench Finder lets you aim at a block and press a key to pull a matching item into your main hand from everywhere.\n\nItem matching is driven by client-side rules with wildcard support and ordered item lists. The mod searches your inventory plus supported storage items from other mods, then equips the first match it can retrieve.
curios_version=15.0.0-beta.2+26.1.2

ae2_version=26.1.6-alpha
tomsstorage_fileid=7917008
refined_storage_fileid=8032789
beyond_dimensions_fileid=7866937
occultism_fileid=8160066
projecte_fileid=6611984


