# org.gradle.java.home=C:/Program Files/Java/dragonwell-17.0.4.0.4+8-GA
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

author=Polaris_Light
modid=wrenchfinder

mcversion=1.20.1
forgeversion=47.4.0
mcp_channel=official
mcp_mappings=1.20.1

cloth_config_version=11.1.136
botania=1.20.1-441-FORGE-SNAPSHOT

l2backpack_fileid=7034933
l2library_fileid=6806000
ae2_fileid=7148487
tomsstorage_fileid=6418133
refinedstorage_fileid=4844585
beyond_dimensions_fileid=7719949

curios_version=5.14.1+1.20.1

version_major=1
version_minor=0
version_patch=1
