# org.gradle.java.home=C:/Program Files/Java/dragonwell-21
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_version=21.1.170
neo_version_range=[21.1.1,)
minecraft_version_range=[1.21,1.22)

mod_id=wrenchfinder
mod_name=Wrench Finder
mod_license=MIT
mod_version=1.0.1
mod_group_id=dev.polaris_light.wrenchfinder
mod_authors=Polaris_Light
mod_description=Wrench Finder lets you aim at a block and press a key to pull a matching item into your main hand from everywhere.\n\nItem matching is driven by client-side rules with wildcard support and ordered item lists. The mod searches your inventory plus supported storage items from other mods, then equips the first match it can retrieve.
curios_version=9.5.1+1.21.1

botania_version=452-SNAPSHOT
l2backpack_fileid=7511415
l2library_fileid=7584599
ae2_version=19.2.17
tomsstorage_fileid=7659872
refined_storage_fileid=7610477
beyond_dimensions_fileid=8142897
occultism_fileid=7336033
projecte_fileid=6611984
